name: Deploy MyAPP
run-name: ${{ github.actor }} is deploying MyAPP 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy-MyAPP:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Config BackEnd file
        run: |
          sed -i 's/DATABASE_USER/${{ secrets.DATABASE_USER }}/g' backend/app/index.js
          sed -i 's/DATABASE_PASSWORD/${{ secrets.DATABASE_PASSWORD }}/g' backend/app/index.js
          sed -i 's/DATABASE_HOST/${{ secrets.DATABASE_HOST }}/g' backend/app/index.js
          sed -i 's/DATABASE_NAME/${{ secrets.DATABASE_NAME }}/g' backend/app/index.js

      - name: Deploy BackEnd
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "backend/app/index.js"
          target: "/home/ubuntu/myapp/"
          strip_components: 1
          debug: true

      - name: Config FrontEnd file
        run: |
          sed -i 's/_API_ADDRESS_/${{ secrets.HOST }}/g' frontend/index.html

      - name: Deploy FrontEnd
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "frontend/*"
          target: "/var/www/html/"
          strip_components: 1
          debug: true
